### ISSUE TITLE
nr.*数据库下载的问题

### ISSUE THREAD

**Issue by LiuBaoYing** [HongWuL/sAMPpred-GAT#1]
您说在https://ftp.ncbi.nlm.nih.gov/blast/db/下载nr.*文件，在这个网站上我看到有nr.xx.tar.gz和nr.xx.tar.gz.md5文件，都要下载码？从nr.00.tar.gz到nr.63.tar.gz都要下载吗？

**Comment by HongWuL** [comment]
Yep
