### ISSUE TITLE
Could not found the database

### ISSUE THREAD

**Issue by yuqing-feng** [HongWuL/sAMPpred-GAT#2]
Thank you for providing us an excellent software to predict the AMPs.

During the installization, I could not found the nrdb90 database (http://bliulab.net/sAMPpred-GAT/static/download/nrdb90.tar.gz).

Would you mind provide an available url?

**Comment by ggcameronnogg** [comment]
i couldn't find it as well

**Comment by HongWuL** [comment]
Since I have already graduated and am unable to make any changes to the web servers in the laboratory, I recommend contacting kyan@bliulab.net via email to obtain the nrdb90.
