### ISSUE TITLE
Unable to download nrdb90.tar.gz

### ISSUE THREAD

**Issue by zyannick** [HongWuL/sAMPpred-GAT#4]
Currently the file is not accessible:
<img width="521" alt="image" src="https://github.com/user-attachments/assets/eebc225e-fc6f-47f4-ba79-89c0069b5aaf">

**Comment by HongWuL** [comment]
Since I have already graduated and am unable to make any changes to the web servers in the laboratory, I recommend contacting [kyan@bliulab.net](mailto:kyan@bliulab.net) via email to obtain the nrdb90.
