### ISSUE TITLE
About HHBlits and Psiblast Data

### ISSUE THREAD

**Issue by Xzz99** [HongWuL/sAMPpred-GAT#5]
The nrdb90 link you provided is invalid. Can you provide the nrdb90 and NR data you used? Thank you.

**Comment by HongWuL** [comment]
> The nrdb90 link you provided is invalid. Can you provide the nrdb90 and NR data you used? Thank you.

Contact [kyan@bliulab.net](mailto:kyan@bliulab.net) to obtain the nrdb90 and NR
